### ISSUE TITLE
[Menguji - Open Challenge] Menunggu accept dari pembuat tantangan

### ISSUE THREAD

**Issue by semilirbayu** [pantaubersama/PemiluAndroid#68]
### Acuan Layout:

- https://app.zeplin.io/project/5c1511a99057185090d7d38e/screen/5c3d030eb7b2dabdd57093d6

### - Header
- [x] wording Open Challenge
- [x] nama pembuat tantangan dan calon lawan yang menerima tantangan (kita)

### - Konten Section
- [x] Wording "Menunggu, _nama user_ untuk konfirmasi lawan debat"
- [x] Image background
- [x] list penerima tantangan
- [x] Avatar, nama dan username penerima tantangan

### - Challenge Detail
- [x] Bidang Kajian
- [x] Pernyataan
- [x] Date & Time
- [x] Saldo Waktu

### - Info Pembuat Tantangan
- [x] Avatar
- [x] Nama
- [x] Bio
- [x] Posted in

**Comment by edityomurti** [comment]
DONE masuk di commit -> https://github.com/pantaubersama/PemiluAndroid/commit/281eb68b77f533266ef6be5a42efabce9e006410#r32602219
